name: Site scanner

on:
  workflow_dispatch:

jobs:
  DAST-scan:
    name: DAST site scanner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        port: [31546, 31547]

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: http://3.76.219.129:31546
          artifact_name: zap_scan_3.76.219.129:31546
